#!/usr/bin/env python3
"""
Convert translation mapping text files to Excel format for analysis.

This script parses the mapping files generated by xliff_to_excel.py and converts
them to Excel format for easier analysis of LLM vs Human translation randomization.

Usage: python mapping_txt_to_xlsx.py <language_code>
Example: python mapping_txt_to_xlsx.py fr
"""

import re
import pandas as pd
import os
import sys
import argparse
from pathlib import Path

def parse_translation_file(file_path):
    """Parse a translation mapping file and extract the mapping data."""
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
    except FileNotFoundError:
        print(f"Error: File not found: {file_path}")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file {file_path}: {e}")
        sys.exit(1)
    
    # Check if the file contains mapping information
    if "Mapping of translations to columns:" not in content:
        print(f"Error: File {file_path} does not contain mapping information")
        sys.exit(1)
    
    # Extract the mapping section
    mapping_section = content.split("Mapping of translations to columns:")[1].strip()
    
    # Initialize lists to store data
    ids = []
    first_translations = []
    second_translations = []
    
    # Pattern to match each translation entry
    pattern = r"ID: (.*?)\n\s+First translation: (.*?)\n\s+Second translation: (.*?)(?=\n-----|$)"
    
    # Find all matches
    matches = re.findall(pattern, mapping_section, re.DOTALL)
    
    if not matches:
        print(f"Warning: No mapping entries found in {file_path}")
        return pd.DataFrame()
    
    # Process matches
    for match in matches:
        id_value = match[0].strip()
        first_translation = match[1].strip()
        second_translation = match[2].strip()
        
        ids.append(id_value)
        first_translations.append(first_translation)
        second_translations.append(second_translation)
    
    # Create DataFrame
    df = pd.DataFrame({
        'ID': ids,
        'First translation': first_translations,
        'Second translation': second_translations
    })
    
    return df

def main():
    parser = argparse.ArgumentParser(
        description='Convert translation mapping text files to Excel format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python mapping_txt_to_xlsx.py fr     # Process French mapping
  python mapping_txt_to_xlsx.py es     # Process Spanish mapping
  python mapping_txt_to_xlsx.py de     # Process German mapping
        """
    )
    parser.add_argument('language_code', 
                        help='Language code (e.g., fr, es, de, it)')
    parser.add_argument('--input-dir', '-i', default='.', 
                        help='Input directory containing mapping files (default: current directory)')
    parser.add_argument('--output-dir', '-o', default='.', 
                        help='Output directory for Excel files (default: current directory)')
    
    args = parser.parse_args()
    
    language_code = args.language_code.lower()
    
    # Construct file paths
    input_file = Path(args.input_dir) / f"mapping_{language_code}.txt"
    output_file = Path(args.output_dir) / f"mapping_{language_code}.xlsx"
    
    # Check if input file exists
    if not input_file.exists():
        print(f"Error: Input file not found: {input_file}")
        print(f"Make sure you have run the translation study for '{language_code}' first.")
        sys.exit(1)
    
    print(f"Processing mapping file for language: {language_code}")
    print(f"Input file: {input_file}")
    
    # Parse the file and get DataFrame
    df = parse_translation_file(input_file)
    
    if df.empty:
        print("No data to process. Exiting.")
        sys.exit(1)
    
    # Create output directory if it doesn't exist
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    # Save to Excel
    try:
        df.to_excel(output_file, index=False)
        print(f"✅ Successfully created Excel file: {output_file}")
        print(f"📊 Processed {len(df)} translation mappings")
        
        # Show summary statistics
        first_llm_count = (df['First translation'] == 'target').sum()
        first_human_count = (df['First translation'] == 'target-classic').sum()
        
        print(f"\n📈 Mapping Summary:")
        print(f"  First column is LLM (target): {first_llm_count} strings")
        print(f"  First column is Human (target-classic): {first_human_count} strings")
        print(f"  Randomization ratio: {first_llm_count}/{len(df)} = {first_llm_count/len(df)*100:.1f}% LLM first")
        
    except Exception as e:
        print(f"Error saving Excel file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
