//
//  DesertColorPalette.swift
//
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import SwiftUI

#if os(macOS)

/// Autogenerated from [Figma](https://www.figma.com/design/lowzSNK3XysASQ1urGCZFp/Browser-Color-Themes?node-id=504-17677&m=dev)
struct DesertColorPalette: SharedColorPaletteDefinition {

    // Accent Colors
    static let accentContentPrimary = DynamicColor(lightHex: 0xfcfcfb, darkHex: 0x17150f)
    static let accentContentSecondary = DynamicColor(lightHex: 0xfdfdfc, lightOpacityHex: 0xb2, darkHex: 0x17150f, darkOpacityHex: 0xb2)
    static let accentContentTertiary = DynamicColor(lightHex: 0xfdfdfc, lightOpacityHex: 0x7f, darkHex: 0x17150f, darkOpacityHex: 0x7f)
    static let accentGlowPrimary = DynamicColor(lightHex: 0xd14200, lightOpacityHex: 0x33, darkHex: 0xffa53d, darkOpacityHex: 0x33)
    static let accentGlowSecondary = DynamicColor(lightHex: 0xd14200, lightOpacityHex: 0x1e, darkHex: 0xffa53d, darkOpacityHex: 0x1e)
    static let accentPrimary = DynamicColor(lightHex: 0xd14200, darkHex: 0xffa43d)
    static let accentQuaternary = DynamicColor(lightHex: 0xa32b00, darkHex: 0xd65900)
    static let accentSecondary = DynamicColor(lightHex: 0xc13600, darkHex: 0xff8914)
    static let accentTertiary = DynamicColor(lightHex: 0xb73000, darkHex: 0xff6a00)
    static let accentTextPrimary = DynamicColor(lightHex: 0xc13600, darkHex: 0xffcc66)
    static let accentTextSecondary = DynamicColor(lightHex: 0xb73000, darkHex: 0xffa43d)
    static let accentTextTertiary = DynamicColor(lightHex: 0xa32b00, darkHex: 0xff6a00)

    // Accent Alt Colors
    static let accentAltContentPrimary = DynamicColor(lightHex: 0x1e42a4, darkHex: 0xccdaff)
    static let accentAltContentSecondary = DynamicColor(lightHex: 0x0b2059, darkHex: 0xe5edff)
    static let accentAltContentTertiary = DynamicColor(lightHex: 0x051133, darkHex: 0xffffff)
    static let accentAltGlowPrimary = DynamicColor(lightHex: 0x7295f6, lightOpacityHex: 0x33, darkHex: 0x8fabf9, darkOpacityHex: 0x33)
    static let accentAltGlowSecondary = DynamicColor(lightHex: 0x7295f6, lightOpacityHex: 0x1e, darkHex: 0x8fabf9, darkOpacityHex: 0x1e)
    static let accentAltPrimary = DynamicColor(lightHex: 0xccdaff, darkHex: 0x2b55ca)
    static let accentAltSecondary = DynamicColor(lightHex: 0xadc2fc, darkHex: 0x1e42a4)
    static let accentAltTertiary = DynamicColor(lightHex: 0x8fabf9, darkHex: 0x14307e)
    static let accentAltTextPrimary = DynamicColor(lightHex: 0x1e42a4, darkHex: 0xccdaff)
    static let accentAltTextSecondary = DynamicColor(lightHex: 0x14307e, darkHex: 0xadc2fc)
    static let accentAltTextTertiary = DynamicColor(lightHex: 0x0b2059, darkHex: 0x8fabf9)

    // Container Colors
    static let containerDecorationPrimary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0x16, darkHex: 0xf9f8f6, darkOpacityHex: 0x1e)
    static let containerDecorationSecondary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0x0f, darkHex: 0xf9f8f6, darkOpacityHex: 0x16)
    static let containerDecorationTertiary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0x0f, darkHex: 0xf9f8f6, darkOpacityHex: 0x16)
    static let containerFillPrimary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0x0f, darkHex: 0xf9f8f6, darkOpacityHex: 0x16)
    static let containerFillSecondary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0x07, darkHex: 0xf9f8f6, darkOpacityHex: 0x0f)
    static let containerFillTertiary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0x02, darkHex: 0xf9f8f6, darkOpacityHex: 0x07)

    // Controls Colors
    static let controlsBase = DynamicColor(lightHex: 0x736249, darkHex: 0xede8de)
    static let controlsDecorationPrimary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0x51, darkHex: 0xede8de, darkOpacityHex: 0x7a)
    static let controlsDecorationSecondary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0x8e, darkHex: 0xede8de, darkOpacityHex: 0xa3)
    static let controlsDecorationTertiary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0xa3, darkHex: 0xede8de, darkOpacityHex: 0xb7)
    static let controlsDecorationQuaternary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0xb7, darkHex: 0xede8de, darkOpacityHex: 0xcc)
    static let controlsFillPrimary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0x16, darkHex: 0xede8de, darkOpacityHex: 0x1e)
    static let controlsFillSecondary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0x1e, darkHex: 0xede8de, darkOpacityHex: 0x2d)
    static let controlsFillTertiary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0x2d, darkHex: 0xede8de, darkOpacityHex: 0x3d)

    // Decoration Colors
    static let decorationPrimary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0x3d, darkHex: 0xede8de, darkOpacityHex: 0x33)
    static let decorationSecondary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0x66, darkHex: 0xede8de, darkOpacityHex: 0x3d)
    static let decorationTertiary = DynamicColor(lightHex: 0x736249, lightOpacityHex: 0x8e, darkHex: 0xede8de, darkOpacityHex: 0x51)

    // Destructive Colors
    static let destructiveContentPrimary = DynamicColor(lightHex: 0xffffff, darkHex: 0x000000)
    static let destructiveContentSecondary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0xe5, darkHex: 0x000000, darkOpacityHex: 0xe5)
    static let destructiveContentTertiary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0x99, darkHex: 0x000000, darkOpacityHex: 0x99)
    static let destructiveGlow = DynamicColor(staticColorHex: 0xee1025, opacity: 0.2)
    static let destructivePrimary = DynamicColor(staticColorHex: 0xee1025)
    static let destructiveSecondary = DynamicColor(staticColorHex: 0xd11527)
    static let destructiveTertiary = DynamicColor(staticColorHex: 0xaa1926)
    static let destructiveTextPrimary = DynamicColor(staticColorHex: 0xee1025)
    static let destructiveTextSecondary = DynamicColor(staticColorHex: 0xd11527)
    static let destructiveTextTertiary = DynamicColor(staticColorHex: 0xaa1926)

    // Highlight Colors
    static let highlightPrimary = DynamicColor(lightHex: 0xfdfaf7, lightOpacityHex: 0x3d, darkHex: 0xf5faf4, darkOpacityHex: 0x1e)

    // Icons Colors
    static let icons = DynamicColor(lightColor: Color(0x1F1F1F).opacity(0.84), darkColor: .tint(0.78))
    static let iconsPrimary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0xd6, darkHex: 0xfdfaf7, darkOpacityHex: 0xc6)
    static let iconsSecondary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0xa8, darkHex: 0xfdfaf7, darkOpacityHex: 0x7a)
    static let iconsTertiary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0x5b, darkHex: 0xfdfaf7, darkOpacityHex: 0x3d)

    // Shadow Colors
    static let shadowPrimary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x0c, darkHex: 0x000000, darkOpacityHex: 0x28)
    static let shadowSecondary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x14, darkHex: 0x000000, darkOpacityHex: 0x3d)
    static let shadowTertiary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x28, darkHex: 0x000000, darkOpacityHex: 0x51)

    // Surface Colors
    static let surface = DynamicColor(lightHex: 0xF9F9F9, darkHex: 0x373737)
    static let surfaceBackdrop = DynamicColor(lightHex: 0xc6b99e, darkHex: 0x1c1916)
    static let surfaceCanvas = DynamicColor(lightHex: 0xfafaf8, darkHex: 0x312e2a)
    static let surfacePrimary = DynamicColor(lightHex: 0xeee9e1, darkHex: 0x3c3833)
    static let surfaceSecondary = DynamicColor(lightHex: 0xf5f3ef, darkHex: 0x524d46)
    static let surfaceTertiary = DynamicColor(lightHex: 0xf8f7f5, darkHex: 0x6e675d)

    // Text Colors
    static let textPrimary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0xf4, darkHex: 0xfdfaf7, darkOpacityHex: 0xf4)
    static let textSecondary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0xa8, darkHex: 0xfdfaf7, darkOpacityHex: 0xa8)
    static let textTertiary = DynamicColor(lightHex: 0x17150f, lightOpacityHex: 0x5b, darkHex: 0xfdfaf7, darkOpacityHex: 0x5b)

    // Tone Colors
    static let toneShadePrimary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x0f, darkHex: 0x161617, darkOpacityHex: 0x51)
    static let toneTintPrimary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0x7a, darkHex: 0xf9f9f9, darkOpacityHex: 0x1e)

    // Missing in Figma JSON Export:
    static let alertGreen = DynamicColor(lightColor: .alertGreen, darkColor: .alertGreen)
    static let alertYellow = DynamicColor(lightColor: .alertYellow, darkColor: .alertYellow)
    static let buttonsPrimaryDefault = DynamicColor(lightColor: .blue50, darkColor: .blue30)
    static let buttonsPrimaryPressed = DynamicColor(lightColor: .blue70, darkColor: .blue50)
    static let buttonsPrimaryDisabled = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsPrimaryText = DynamicColor(lightColor: .white, darkColor: .shade(0.84))
    static let buttonsPrimaryTextDisabled = DynamicColor(lightColor: .shade(0.36), darkColor: .tint(0.36))
    static let buttonsSecondaryFillDefault = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsSecondaryFillPressed = DynamicColor(lightColor: .shade(0.18), darkColor: .tint(0.3))
    static let buttonsSecondaryFillDisabled = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsSecondaryFillText = DynamicColor(lightColor: .shade(0.84), darkColor: .white)
    static let buttonsSecondaryFillTextDisabled = DynamicColor(lightColor: .shade(0.36), darkColor: .tint(0.36))
    static let buttonsWhite = DynamicColor(lightColor: .white, darkColor: .black)
    static let lines = DynamicColor(lightHex: 0x1F1F1F, lightOpacity: 0.09, darkHex: 0xF9F9F9, darkOpacity: 0.12)
}

#endif
