//
//  GreenColorPalette.swift
//
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import SwiftUI

#if os(macOS)

/// Autogenerated from [Figma](https://www.figma.com/design/lowzSNK3XysASQ1urGCZFp/Browser-Color-Themes?node-id=504-17677&m=dev)
struct GreenColorPalette: SharedColorPaletteDefinition {
    static let accentContentPrimary = DynamicColor(lightHex: 0xf5fbf4, darkHex: 0x0b1914)
    static let accentContentSecondary = DynamicColor(lightHex: 0xf5fbf4, lightOpacityHex: 0xb2, darkHex: 0x0b1914, darkOpacityHex: 0xb2)
    static let accentContentTertiary = DynamicColor(lightHex: 0xf5fbf4, lightOpacityHex: 0x7f, darkHex: 0x0b1914, darkOpacityHex: 0x7f)
    static let accentGlowPrimary = DynamicColor(lightHex: 0x388056, lightOpacityHex: 0x33, darkHex: 0x6ec7a2, darkOpacityHex: 0x33)
    static let accentGlowSecondary = DynamicColor(lightHex: 0x388056, lightOpacityHex: 0x1e, darkHex: 0x6ec7a2, darkOpacityHex: 0x1e)
    static let accentPrimary = DynamicColor(lightHex: 0x377f55, darkHex: 0x6ec7a2)
    static let accentQuaternary = DynamicColor(lightHex: 0x183826, darkHex: 0x21815a)
    static let accentSecondary = DynamicColor(lightHex: 0x2c6645, darkHex: 0x48b186)
    static let accentTertiary = DynamicColor(lightHex: 0x235136, darkHex: 0x299c6d)
    static let accentTextPrimary = DynamicColor(lightHex: 0x2c6645, darkHex: 0x85e0ba)
    static let accentTextSecondary = DynamicColor(lightHex: 0x235136, darkHex: 0x6ec7a2)
    static let accentTextTertiary = DynamicColor(lightHex: 0x193926, darkHex: 0x48b186)
    static let containerBorderPrimary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x0f, darkHex: 0xf5faf4, darkOpacityHex: 0x16)
    static let containerBorderSecondary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x16, darkHex: 0xf5faf4, darkOpacityHex: 0x1e)
    static let containerBorderTertiary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x1e, darkHex: 0xf5faf4, darkOpacityHex: 0x28)
    static let containerFillPrimary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x02, darkHex: 0xf5faf4, darkOpacityHex: 0x07)
    static let containerFillSecondary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x07, darkHex: 0xf5faf4, darkOpacityHex: 0x0f)
    static let containerFillTertiary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x0f, darkHex: 0xf5faf4, darkOpacityHex: 0x16)
    static let controlsBorderPrimary = DynamicColor(lightHex: 0x288a51, lightOpacityHex: 0x51, darkHex: 0x88ddba, darkOpacityHex: 0x3d)
    static let controlsBorderQuaternary = DynamicColor(lightHex: 0x288a51, lightOpacityHex: 0xb7, darkHex: 0x88ddba, darkOpacityHex: 0xcc)
    static let controlsBorderSecondary = DynamicColor(lightHex: 0x288a51, lightOpacityHex: 0x8e, darkHex: 0x88ddba, darkOpacityHex: 0xa3)
    static let controlsBorderTertiary = DynamicColor(lightHex: 0x288a51, lightOpacityHex: 0xa3, darkHex: 0x88ddba, darkOpacityHex: 0xb7)
    static let controlsFillPrimary = DynamicColor(lightHex: 0x288a51, lightOpacityHex: 0x16, darkHex: 0x88ddba, darkOpacityHex: 0x1e)
    static let controlsFillSecondary = DynamicColor(lightHex: 0x288a51, lightOpacityHex: 0x1e, darkHex: 0x88ddba, darkOpacityHex: 0x2d)
    static let controlsFillTertiary = DynamicColor(lightHex: 0x288a51, lightOpacityHex: 0x2d, darkHex: 0x88ddba, darkOpacityHex: 0x3d)
    static let highlightPrimary = DynamicColor(lightHex: 0xf5faf4, lightOpacityHex: 0x3d, darkHex: 0xe6f2ea, darkOpacityHex: 0x1e)
    static let iconsPrimary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0xd6, darkHex: 0xe6f2ea, darkOpacityHex: 0xc6)
    static let iconsSecondary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x99, darkHex: 0xe6f2ea, darkOpacityHex: 0x7a)
    static let iconsTertiary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x5b, darkHex: 0xe6f2ea, darkOpacityHex: 0x3d)
    static let surfaceBackdrop = DynamicColor(lightHex: 0xb5d0ad, darkHex: 0x0f241c)
    static let surfaceCanvas = DynamicColor(lightHex: 0xecf5ea, darkHex: 0x1c342b)
    static let surfaceDecorationPrimary = DynamicColor(lightHex: 0x1f9350, lightOpacityHex: 0x3d, darkHex: 0x88ddba, darkOpacityHex: 0x33)
    static let surfaceDecorationSecondary = DynamicColor(lightHex: 0x1f9350, lightOpacityHex: 0x66, darkHex: 0x88ddba, darkOpacityHex: 0x3d)
    static let surfaceDecorationTertiary = DynamicColor(lightHex: 0x1f9350, lightOpacityHex: 0x8e, darkHex: 0x88ddba, darkOpacityHex: 0x51)
    static let surfacePrimary = DynamicColor(lightHex: 0xe3eee1, darkHex: 0x203b30)
    static let surfaceSecondary = DynamicColor(lightHex: 0xecf4eb, darkHex: 0x294639)
    static let surfaceTertiary = DynamicColor(lightHex: 0xf5faf4, darkHex: 0x315343)
    static let textPrimary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0xf4, darkHex: 0xf2f8f4, darkOpacityHex: 0xf4)
    static let textSecondary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0xa8, darkHex: 0xf2f8f4, darkOpacityHex: 0xa8)
    static let textTertiary = DynamicColor(lightHex: 0x062504, lightOpacityHex: 0x5b, darkHex: 0xf2f8f4, darkOpacityHex: 0x5b)

    // MARK: - Inherited from FigmaColorPalette

    static let accentAltContentPrimary = DynamicColor(lightHex: 0x1e42a4, darkHex: 0xccdaff)
    static let accentAltContentSecondary = DynamicColor(lightHex: 0x0b2059, darkHex: 0xe5edff)
    static let accentAltContentTertiary = DynamicColor(lightHex: 0x051133, darkHex: 0xffffff)
    static let accentAltGlowPrimary = DynamicColor(lightHex: 0x7295f6, lightOpacityHex: 0x33, darkHex: 0x8fabf9, darkOpacityHex: 0x33)
    static let accentAltGlowSecondary = DynamicColor(lightHex: 0x7295f6, lightOpacityHex: 0x1e, darkHex: 0x8fabf9, darkOpacityHex: 0x1e)
    static let accentAltPrimary = DynamicColor(lightHex: 0xccdaff, darkHex: 0x2b55ca)
    static let accentAltSecondary = DynamicColor(lightHex: 0xadc2fc, darkHex: 0x1e42a4)
    static let accentAltTertiary = DynamicColor(lightHex: 0x8fabf9, darkHex: 0x14307e)
    static let accentAltTextPrimary = DynamicColor(lightHex: 0x1e42a4, darkHex: 0xccdaff)
    static let accentAltTextSecondary = DynamicColor(lightHex: 0x14307e, darkHex: 0xadc2fc)
    static let accentAltTextTertiary = DynamicColor(lightHex: 0x0b2059, darkHex: 0x8fabf9)

    static let destructiveContentPrimary = DynamicColor(lightHex: 0xffffff, darkHex: 0x000000)
    static let destructiveContentSecondary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0xe5, darkHex: 0x000000, darkOpacityHex: 0xe5)
    static let destructiveContentTertiary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0x99, darkHex: 0x000000, darkOpacityHex: 0x99)
    static let destructiveGlow = DynamicColor(lightHex: 0xee1025, lightOpacityHex: 0x33, darkHex: 0xee1025, darkOpacityHex: 0x33)
    static let destructivePrimary = DynamicColor(lightHex: 0xee1025, darkHex: 0xee1025)
    static let destructiveSecondary = DynamicColor(lightHex: 0xd11527, darkHex: 0xd11527)
    static let destructiveTertiary = DynamicColor(lightHex: 0xaa1926, darkHex: 0xaa1926)
    static let destructiveTextPrimary = DynamicColor(lightHex: 0xee1025, darkHex: 0xee1025)
    static let destructiveTextSecondary = DynamicColor(lightHex: 0xd11527, darkHex: 0xd11527)
    static let destructiveTextTertiary = DynamicColor(lightHex: 0xaa1926, darkHex: 0xaa1926)

    // MARK: - Not Specialized

    static let alertGreen = DynamicColor(lightColor: .alertGreen, darkColor: .alertGreen)
    static let alertYellow = DynamicColor(lightColor: .alertYellow, darkColor: .alertYellow)

    static let buttonsWhite = DynamicColor(lightColor: .white, darkColor: .black)

    static let buttonsPrimaryDefault = DynamicColor(lightColor: .blue50, darkColor: .blue30)
    static let buttonsPrimaryPressed = DynamicColor(lightColor: .blue70, darkColor: .blue50)
    static let buttonsPrimaryDisabled = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsPrimaryText = DynamicColor(lightColor: .white, darkColor: .shade(0.84))
    static let buttonsPrimaryTextDisabled = DynamicColor(lightColor: .shade(0.36), darkColor: .tint(0.36))

    static let buttonsSecondaryFillDefault = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsSecondaryFillPressed = DynamicColor(lightColor: .shade(0.18), darkColor: .tint(0.3))
    static let buttonsSecondaryFillDisabled = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsSecondaryFillText = DynamicColor(lightColor: .shade(0.84), darkColor: .white)
    static let buttonsSecondaryFillTextDisabled = DynamicColor(lightColor: .shade(0.36), darkColor: .tint(0.36))

    static let shadowPrimary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x0c, darkHex: 0x000000, darkOpacityHex: 0x28)
    static let shadowSecondary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x14, darkHex: 0x000000, darkOpacityHex: 0x3d)
    static let shadowTertiary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x28, darkHex: 0x000000, darkOpacityHex: 0x51)

    static let lines = DynamicColor(lightHex: 0x1F1F1F, lightOpacity: 0.09, darkHex: 0xF9F9F9, darkOpacity: 0.12)
    static let toneShadePrimary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x0f, darkHex: 0x161617, darkOpacityHex: 0x51)
}

#endif
